# Site settings
title: Antonio Pedro Ferreira - Sonhador, Empreendedor, Engenheiro de Software, Musico e muito mais
description: Um blog sobre tecnologia, musica, meus causos e afins.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://antoniopedro.com.br" # the base hostname & protocol for your site e.g. http://google.com.br

# User settings
username: Antonio Pedro
user_description: preparar uma boa descrição
email: contato@antoniopedro.com.br
twitter_username: sochins
github_username:  apsferreira
gplus_username:  apsf88
disqus_username: naosei

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: Sobre mim
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
